version: 0.2
phases:
  install:
    runtime-versions:
      java: 17
  pre_build:
    commands:
      - echo In the pre_build phase... nothing to do here
  build:
    commands:
      - echo Build started on `date`
      - ./mvnw clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/allure-shop.jar
    - appspec.yml
